[package]
name = "fastembed"
version = "4.9.1"
edition = "2021"
description = "Library for generating vector embeddings, reranking locally."
license = "Apache-2.0"
authors = [
  "Anush008 <anushshetty90@gmail.com>",
  "Josh Niemelä <josh@jniemela.dk>",
  "GrisiaEvy <a115020115@gmail.com>",
  "George MacKerron <georgemackerron@neon.tech>",
  "Timon Vonk <mail@timonv.nl>",
  "Luya Wang <luya.wang@qq.com>",
  "Tri <tri@triandco.com>",
  "Denny Wong <denwong47@hotmail.com>",
  "Alex Rozgo <alex.rozgo@gmail.com>",
]
documentation = "https://docs.rs/fastembed"
repository = "https://github.com/Anush008/fastembed-rs"
homepage = "https://crates.io/crates/fastembed"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tokenizers is now target-specific

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokenizers = { version = "0.21", default-features = false, features = ["onig"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokenizers = { version = "0.21", default-features = false, features = ["unstable_wasm"] }

anyhow = { version = "1" }
hf-hub = { version = "0.4.1", default-features = false, optional = true }
image = "0.25.2"
ndarray = { version = "0.16", default-features = false }
ort = { version = "=2.0.0-rc.9", default-features = false, features = [
  "ndarray",
] }
rayon = { version = "1.10", default-features = false }
serde_json = { version = "1" }

ort-sys = { version = "=2.0.0-rc.9", default-features = false }

[features]
ort-download-binaries = ["ort/download-binaries"]
ort-load-dynamic = ["ort/load-dynamic"]
hf-hub = ["dep:hf-hub", "hf-hub?/ureq"]
hf-hub-native-tls = ["hf-hub", "hf-hub?/native-tls"]
hf-hub-rustls-tls = ["hf-hub", "hf-hub?/rustls-tls"]
optimum-cli = []
online = ["hf-hub-native-tls"]

# For native targets, default includes native-tls (may pull in OpenSSL)
default = ["ort-download-binaries", "hf-hub-native-tls"]

# For wasm32, override default to use rustls (WASM-safe)
[target.'cfg(target_arch = "wasm32")'.features]
default = ["ort-download-binaries", "hf-hub-rustls-tls"]
